### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by bernatfortet** [dparlevliet/node.bittrex.api#2] opened 2017-09-10 23:13 UTC
I'm running `bittrex.websockets.subscribe.example` without touching anything and I'm getting:

```
Error Message:  Negotiate Unknown
Exception:  undefined
Error Data:  503
```

Any idea on what's going on?

Thanks!

**Comment by dparlevliet** [comment] 2017-09-10 23:21
Is this a consistent issue or intermittent? The issue is Bittrex has changed to using Cloudflare with strict browser checking - we have attempted to get around it using ``cloudscraper``, which is working for everyone so far but it seems you're still being blocked, or at least that attempt was. The fix is still working for me, consistently, so I'm not sure why it wouldn't work for you specifically.

**Comment by glaucoheitor** [comment] 2017-09-11 00:30
It isn't working for me also as I stated on the other repo.

The only way I found to work is to comment out the cloudscrapper thing and put the cf and UA directly to signalr file.

**Comment by dparlevliet** [comment] 2017-09-11 00:38
@glaucoheitor can you be more specific about what you actually do to make it work for you? Examples will help me greatly - it's very hard for me to fix a problem I can't replicate.

**Comment by glaucoheitor** [comment] 2017-09-11 00:44
Sure, sorry for not being complete. English isn't my main language so I may struggle sometimes.

I edit the signalR.js file inside clientInterface function.
I add cookie and UA to "headers" object manually and then the code works) after I comment out the cloudscrapper thing.

I tried to put a console.log line after line 147 in your code to make sure it is entering cloudscrape function but when I run my code it doesn't show it.

Thank you mate

**Comment by dparlevliet** [comment] 2017-09-11 00:54
I see, thanks for that @glaucoheitor. So that would actually be a different issue than what @bernatfortet is experiencing. The only reason I can think of for you not getting a response from the cloudscraper package is that Cloudflare is asking your bot to complete a captcha test, or your bots IP is banned (in the event your bot is running on a different IP to the one you use yourself). Note from the cloudscraper package:

```
In general, CloudFlare has 4 types of common anti-bot pages:
    Simple html+javascript page with challenge
    Page which redirects to original site
    Page with recaptcha
    Page with error ( your ip was banned, etc)

**Unfortunatelly there is no solution, if website is protected by captcha.**
```

So, with that in-mind, perhaps I will make the cloudscraper method optional and provide you the method to attach the US and CF cookie to the settings manually. You should not need to modify signalR directly because it has the option to provide additional headers, which is what we are doing.

I'll make the options available later today and then you can test it and let me know if it suits your needs.

**Comment by dparlevliet** [comment] 2017-09-11 00:58
@bernatfortet would you mind adding a console.log to line 148 (inside ``cloudscraper.get``) and checking to see if it gets hit? That would help me determine if you're likely getting the captcha response from Cloudflare too.

**Comment by glaucoheitor** [comment] 2017-09-11 01:00
I thought that maybe would be captcha or banning issue, but when I run clouscrape all by it self I can get the info. That's the way I get the info to manually add to signalR.

**Comment by dparlevliet** [comment] 2017-09-11 01:01
erm, well that makes no sense. So, you run ``cloudscraper.get('https://bittrex.com/', function(error, response, body) { .. });`` in a different script and it works for you?

**Comment by glaucoheitor** [comment] 2017-09-11 01:02
I run this code and it reply with UA and cookie. I get this data and put manually on signalR

```
var cloudscraper = require('cloudscraper');
cloudscraper.get('https://bittrex.com/', function(error, response, body) {
    if (error) { 
        console.log(error);
    } else {
        var headers = response.socket._httpMessage._header;
        var regexp_user_agent = /User-Agent: (.*?)\r\n/;
        var regexp_cf_clearance = /(cf_clearance=.*?)\r\n/;
        
        var user_agent = headers.match(regexp_user_agent)[1];
        var cf_clearance = headers.match(regexp_cf_clearance)[1];

        console.log(user_agent, cf_clearance);
    }
});
```

**Comment by dparlevliet** [comment] 2017-09-11 01:07
Well that's just odd. If you put a console.log on line 146 (before cloudscraper) in this package does that get hit? Checking to see if it's even making it to the cloudscraper request at all.

**Comment by glaucoheitor** [comment] 2017-09-11 01:14
Nope. I doesn't.

Let me add here the code I am using. It's the same I was using from the other repo.

```
//Bittrex ticker
var websocketsclient = bittrex.websockets.client();

websocketsclient = bittrex.websockets.subscribe(['USDT-BTC'], function(data) {
	if (data.M === 'updateExchangeState') {
		data.A.forEach(function(data_for) {
		//my code
		});
	}
});
	
websocketsclient.serviceHandlers.disconnected = (websocket) => {
	console.log("bittrex disconnected, reconnecting immediately");
	setImmediate(() => {
		websocketsclient.start();
	});
}
```

**Comment by dparlevliet** [comment] 2017-09-11 01:18
OK, thanks, so now we know the issue isn't cloudscraper - for you at least. Can you tell me what version of node you're using?

Also note, that code in general wont work anymore because connecting to websockets is now asynchronous with the new requirements - please see the new examples in the ``examples/`` folder and new documentation in the ``README.md``.

**Comment by glaucoheitor** [comment] 2017-09-11 01:22
I see. but I think the way my code is written it should work with the new requirements, right?

I am using version  node: '8.0.0',

**Comment by dparlevliet** [comment] 2017-09-11 01:22
@glaucoheitor I just pushed a fix for a small issue which could have been causing the error in the code you provided -- ``client()`` expected a callback, but this is now optional. Additionally, can you please run ``nodejs examples/bittrex.websockets.subscribe.example.js`` and see if that works for you.

**Comment by dparlevliet** [comment] 2017-09-11 01:25
I will do some further testing and make the cloudscraper optional anyway and I'll see if I can make changes that make it work for you

**Comment by glaucoheitor** [comment] 2017-09-11 01:27
Example Subscribe works but my code no yet. I am pretty sure now it is cause of my own code. But I don't have that much knowledge in node to find it hahaha

Thank you very much for all the help!

**Comment by bernatfortet** [comment] 2017-09-11 06:11
@dparlevliet thanks for the hints. After you mentioning cloudscraper I saw that I didn't have the package.
I realized that `npm install node.bittrex.api` still installs 0.6.6 from n0mad01.

I'll try the "advanced" approach, but it would be awesome if npm's repository could be updated

**Comment by dparlevliet** [comment] 2017-09-11 06:14
@bernatfortet I see, thanks for letting me know. Yeah, unfortunately the previous owner hasn't given me access to update the npm repository yet. If he doesn't organise it soon then I will have to rename the package, because that's the only way I can get it on npmjs, but I'm hoping to avoid having to do that.

**Comment by smhty** [comment] 2017-09-11 06:16
Hi guys, I also get the same error:
Error Message:  Negotiate Unknown
Exception:  undefined
Error Data:  503

**Comment by dparlevliet** [comment] 2017-09-11 06:16
@smhty you will need to manually download and install this package

**Closed** 2017-09-11 06:16 UTC

**Comment by smhty** [comment] 2017-09-11 06:19
You mean the "cloudscraper" package?

**Comment by bernatfortet** [comment] 2017-09-11 06:21
@dparlevliet i've sent PR to fix the url in the reamde instructions to reflect your repo
https://github.com/dparlevliet/node.bittrex.api/pull/4/files
