### ISSUE TITLE
Listen method stopped working

### ISSUE THREAD

**Issue by VasilySizov** [dparlevliet/node.bittrex.api#72] opened 2017-11-27 04:37 UTC
Hi! Looks like "listen" method stopped working. It connects, but no messages are received.
You can check out this behavior with the included code example: https://github.com/dparlevliet/node.bittrex.api/blob/master/examples/bittrex.websockets.listen.example.js

It connects, listens, then socket is closed with idle time out after some time.

**Comment by rspenc29** [comment] 2017-11-29 02:57
Here's a fix

https://github.com/dparlevliet/node.bittrex.api/issues/67#issuecomment-346277723

Not sure why the issue is closed. Either the example should be updated or the code should be fixed to work like the example shows.

**Comment by dparlevliet** [comment] 2017-12-01 09:54
The example is updated? https://github.com/dparlevliet/node.bittrex.api#websocketslisten

**Closed** 2017-12-04 01:21 UTC
