### ISSUE TITLE
Websocket Disconnected

### ISSUE THREAD

**Issue by gerardo15** [dparlevliet/node.bittrex.api#67] opened 2017-11-14 09:32 UTC
Hello

I had long time without suffering from this. last night it got disconnected and did not connect again.

I have this function.. wich fires the console.log but does not restart the client

`var websocketsclient2;
bittrex.websockets.listen(function (data, client) { 

    websocketsclient2 = client;
    websocketsclient2.serviceHandlers.disconnected = function (error) {
        setImmediate(function () {
            console.log('Websocket disconnected..' + error + ' expecting retry');
            websocketsclient2.start();
        });
    };

`

**Comment by wenjieitk** [comment] 2017-11-15 03:55
same here, I tried 

```
            client.serviceHandlers.reconnecting = function (message) {
                console.log(exchange + " websocket reconnecting");

                setTimeout(backupCoins, getRemainingTime(granularity.minute, new Date()) + (5 * timeToMilis.minute));
                return false;
            }
```

but it doesn't work as well

**Comment by kristopherlarson** [comment] 2017-11-16 21:24
Yes Im experiencing the same issues where I get disconnected from the socket and it won't restart again until I restart my entire app. Does anyone have a solution for ?

**Comment by dparlevliet** [comment] 2017-11-17 11:00
This is a very difficult thing to fix - I have noticed that the Bittrex website is having significant websocket issues as well. I suspect because Bittrex turned on cloudflare that they're under attack and have been for a while.

As a quick patch I would have a variable which keeps track of the last time data was received and periodically check that timestamp and force a new connection if no data has been received for 30s, and keep trying every 30s until a connection is established. It's possible it disconnected and then was unable to reconnect? Very hard to say with this type of issue.

**Comment by kristopherlarson** [comment] 2017-11-17 14:55
Dparleviet,

Can you provide a quick example on how you would force a new connection after checking the timestamp.

**Comment by webworker01** [comment] 2017-11-17 19:39
If this helps, this is the message I get after disconnection:

`Websocket disconnected
Websocket auto reconnecting.
Websocket onerror:  Negotiate Unknown
Connection aborted
`

**Comment by dparlevliet** [comment] 2017-11-17 20:15
```
const MyWebsocket = function() {
  var self = this;

  self.timestamp = (new Date()).getTime();

  self.connect = (callback) => {
    bittrex.websockets.client((client) => {
      callback(client);
    });
  };

  self.subscribe = (markets, callback) => {
    bittrex.websockets.subscribe(markets, (data, client) => {
      self.timestamp = (new Date()).getTime();
      callback(data, client);
    });
  };

  self.listen = (callback) => {
    bittrex.websockets.subscribe((data, client) => {
      self.timestamp = (new Date()).getTime();
      callback(data, client);
    });
  };

  return self;
};

bittrex.options({
  websockets: {
    autoReconnect: false,
    onConnect: function() {
      console.log('Websocket connected');
    },
    onDisconnect: function() {
      console.log('Websocket disconnected');
      setupWebsocket();
    }
  }
});


var websocket;
var websocketInterval;
const setupWebsocket = () => {
  if (websocketInterval) {
    clearInterval(websocketInterval);
  }

  websocket = new MyWebsocket();

  websocket.connect((client) => {
    websocket.subscribe(['USDT-ETH'], (data, client) => {

    });
  });

  setInterval(() => {
    let now = (new Date()).getTime();
    if ((now - websocket.timestamp) > 60 * 1000) {
      try { websocket.client.end(); } catch (e) {} // try disconnect first
      setupWebsocket();
    }
  }, 10 * 1000);
};
```

**Comment by dparlevliet** [comment] 2017-11-17 22:08
@webworker01 yep that confirms my suspicion - the error and the abort are fatal connection errorr from SignalR. It doesn't pass on the error so there's no way for me to be able to intercept and respond. My above mock solution should compensate for those situations.

**Comment by webworker01** [comment] 2017-11-17 23:45
@dparlevliet Thanks, I will try to implement this into my bot over the weekend and report back!

**Comment by dparlevliet** [comment] 2017-11-17 23:55
Actually had to make a change to the code to be able to force a new connection. Download the latest npm

**Comment by kristopherlarson** [comment] 2017-11-18 02:56
With the new new code do we still need to use the code above as well?

**Comment by sergkush** [comment] 2017-11-18 02:56
@kristopherlarson yes

**Comment by kristopherlarson** [comment] 2017-11-18 03:11
@dparlevliet can you email me personally kristopherlarson@live.com  I would give a donation if you can implement your fix into my code. I'm a php developer not a node developer this seems a bit foreign to me.

**Comment by wenjieitk** [comment] 2017-11-18 09:02
can someone here provide a working examples ?

**Comment by webworker01** [comment] 2017-11-18 09:03
@dparlevliet @wenjieitk the example posted seems to work, i have it running on my dev copy

**Comment by wenjieitk** [comment] 2017-11-18 09:06
@webworker01  glad to hear that ! Please update us if you get to test it out ! Thanks!

**Comment by themagicmountain** [comment] 2017-11-18 17:08
If the underlying problem is signalr-client maybe one of us should create a pull request to that project? Or is there some reason that we're hacking in this library instead? (I am new to open source, so excuse me if this is a dumb question!)

**Comment by aloysius-pgast** [comment] 2017-11-18 18:10
In case anyone is interested, I started to work on an alternative to signalr-client because of disconnect/reconnect pb. Feel free to give it a look https://github.com/aloysius-pgast/bittrex-signalr-client

**Comment by dparlevliet** [comment] 2017-11-18 22:46
Glad to hear the patch is working for everyone - I'll try work it in to the library as an official solution controlled by ``autoReconnect`` - so if you've used the above mock keep an eye on this thread because you'll need to change ``autoReconnect`` back to ``true`` once the patch is done.

An issue was raised for this issue with SignalR-client a long time ago.

**Comment by webworker01** [comment] 2017-11-19 01:51
Okay, I have the code running in my live bot.. we'll see if it reconnects successfully whenever the error pops up.

**Comment by webworker01** [comment] 2017-11-19 08:25
I'm not certain it fixes the issue.. I can see it attempt to reconnect but new data is not streamed.

**Comment by wenjieitk** [comment] 2017-11-19 08:26
@webworker01  same here

**Comment by gerardo15** [comment] 2017-11-19 08:26
I think there is a on going problem.. My node is connected but not getting any bittrex data

**Comment by webworker01** [comment] 2017-11-19 09:14
Have you guys tried to implement this solution as well? I am trying to find out where the new force parameter is or should be used.

**Comment by xitake** [comment] 2017-11-19 12:06
As @gerardo15 mentioned, since 7AM UTC I'm not receiving any data from websocket... and this problem is still on going... Anyone else? I think it's something on Bittrex's side.

**Comment by HonoldMatoma** [comment] 2017-11-19 15:39
I'm also not getting any data from the websocket connection.

**Comment by HonoldMatoma** [comment] 2017-11-19 15:49
There was an update 7h ago, maybe it has something to do with that? https://twitter.com/BittrexExchange/status/932173635447431168

**Comment by dparlevliet** [comment] 2017-11-19 19:00
I'm receiving data fine. Is the issue fixed now?

```
  Bittrex websocket API
    ✓ Connect to the Websocket (10991ms)
Market Update for BTC-ETH { MarketName: 'BTC-ETH',
  Nounce: 37928,
  Buys: 
   [ { Type: 1, Rate: 0.04390513, Quantity: 0 },
     { Type: 0, Rate: 0.04388132, Quantity: 1.42250248 },
     { Type: 0, Rate: 0.04372846, Quantity: 33.792 },
     { Type: 1, Rate: 0.04372844, Quantity: 0 },
     { Type: 0, Rate: 0.04357904, Quantity: 45.056 },
     { Type: 1, Rate: 0.04357903, Quantity: 0 },
     { Type: 1, Rate: 0.04357594, Quantity: 0 },
     { Type: 2, Rate: 0.0435716, Quantity: 0.56 },
     { Type: 0, Rate: 0.04122174, Quantity: 0.01565856 },
     { Type: 0, Rate: 0.04114411, Quantity: 0.01339329 },
     { Type: 0, Rate: 0.04104707, Quantity: 0.0157252 },
     { Type: 0, Rate: 0.04095003, Quantity: 0.01345676 },
     { Type: 0, Rate: 0.0408724, Quantity: 0.0157924 },
     { Type: 0, Rate: 0.04075596, Quantity: 0.01352084 },
     { Type: 0, Rate: 0.04069773, Quantity: 0.01586018 },
     { Type: 0, Rate: 0.04056188, Quantity: 0.01358554 },
     { Type: 0, Rate: 0.04052306, Quantity: 0.01592854 },
     { Type: 0, Rate: 0.0403678, Quantity: 0.01365085 },
     { Type: 1, Rate: 0.00892436, Quantity: 0 },
     { Type: 1, Rate: 0.00885573, Quantity: 0 },
     { Type: 1, Rate: 0.00884503, Quantity: 0 },
     { Type: 1, Rate: 0.00881949, Quantity: 0 },
     { Type: 1, Rate: 0.0086831, Quantity: 0 },
     { Type: 1, Rate: 0.00866031, Quantity: 0 },
     { Type: 1, Rate: 0.00861023, Quantity: 0 },
     { Type: 1, Rate: 0.00859368, Quantity: 0 },
     { Type: 1, Rate: 0.00858358, Quantity: 0 } ],
  Sells: 
   [ { Type: 0, Rate: 0.0442786, Quantity: 2.15078661 },
     { Type: 1, Rate: 0.04429671, Quantity: 0 },
     { Type: 1, Rate: 0.04434545, Quantity: 0 },
     { Type: 1, Rate: 0.04443902, Quantity: 0 },
     { Type: 0, Rate: 0.04444104, Quantity: 0.90006895 },
     { Type: 1, Rate: 0.04444956, Quantity: 0 },
     { Type: 0, Rate: 0.04447853, Quantity: 12.43060884 },
     { Type: 0, Rate: 0.04481032, Quantity: 0.05713941 },
     { Type: 1, Rate: 0.04913204, Quantity: 0 },
     { Type: 0, Rate: 0.05237886, Quantity: 0.11543647 } ],
  Fills: [] }


  1 passing (11s)
```

**Comment by xitake** [comment] 2017-11-19 19:08
Now that you mentioned, I tested the bittrex.websockets.subscribe.example.js from examples folder and it works. How ever, the script bittrex.websockets.client.js doesn't work... I guess we now must subscribe to the markets? Until yesterday we could listen to all markets

**Comment by dparlevliet** [comment] 2017-11-19 19:17
Yep, you're right - they've stopped sending the global data. Even on their website it's just sending ``{}`` which is why people are seeing the error ``{ unhandled_data: {} }``

**Comment by kristopherlarson** [comment] 2017-11-19 19:19
Dang bittrex is really screwing us over. So is the node.bittrex.api setup for this new configuration?

**Comment by dparlevliet** [comment] 2017-11-19 19:19
what new configuration?

**Comment by xitake** [comment] 2017-11-19 19:20
Is there anyway I can subscribe to a given market and received the same data as they used to send as global data? Last price, Volume 24 hours, High price 24 hours, and so on?

**Comment by kristopherlarson** [comment] 2017-11-19 19:21
The bittrex.websockets.listen doesn't seem to work anymore. Do we have to manually configure which markets we want to listen to. Similar to how we subscribe to markets for market buy and sell history.

**Comment by kristopherlarson** [comment] 2017-11-19 19:30
This is from there slack channel not sure if its helpful on what they changed.

> @channel I'm making a change to default socket behavior, updateSummaryState messages will be opt in as of next build (going out later this evening).  There will be explicit subscribe call if you still want to receive summary state messages

**Comment by dparlevliet** [comment] 2017-11-19 19:31
Nope, the ticker data is gone from the websockets completely - they're not even polling the market summaries on their website unless you're on a specific coin's page then it polls the summary for that coin only. 

Right now the only thing the websockets is delivering is the order books.

The only thing you could do for now is periodically poll ``getmarketsummaries``

**Comment by dparlevliet** [comment] 2017-11-19 19:31
@kristopherlarson thanks

**Comment by kristopherlarson** [comment] 2017-11-19 19:33
Interesting, I wonder if this is a temporary thing.

**Comment by xitake** [comment] 2017-11-19 20:05
How often I can call getmarketsummaries? Is there any api call limit in bittrex? I need to fetch data from all markets every 3 seconds

**Comment by kristopherlarson** [comment] 2017-11-19 20:10
Yes hitting there server everything 3 seconds will probably get you banned. The websocket was forsure the best solution but not we don't have it......

 As long as you hit there server from different IP addresses every 3 seconds you could pull it off. Before I used the websocket I was hitting there server every 30 seconds and didn't have issues. I guess the hard part is going to be timing everything out if you start using different IP addresses.

**Comment by dparlevliet** [comment] 2017-11-19 20:29
Every 3 seconds would be fine. You get about 15 requests per second before you get banned, from memory. I always had my bot querying ``getmarketsummaries`` on repeat because it took 2-3s to download so just make sure you're not doing overlapping queries.

**Comment by PeroPrepper** [comment] 2017-11-19 20:41
If I get banned for calling getmarketsummaries every few seconds, is my account banned or just my IP? I use seperate node-bittrex-api instances for public and market API calls, so for public api calls i do not provide API key, but both make calls from same IP. Well you mentioned every 3 seconds would be fine, but there is no official info on acceptable api call rates so we are really kind of in the dark here. I hope sockets come back or at least some way of getting market summaries, without that API is useless to me.

**Comment by kristopherlarson** [comment] 2017-11-19 20:53
I just started hitting there API every 5 seconds for market summary I will let you know if I run into issues.  I really hope we stop having socket issues with the buy sell history now they free'd up some server power.

**Comment by HonoldMatoma** [comment] 2017-11-19 21:08
@PeroPrepper just your IP from my experience. My IP was banned once because of an issue in my script that called an endpoint multiple times in less than a second. After setting a new IP I was able to call endpoints again, I didn't even have to reset my API key.

**Comment by kristopherlarson** [comment] 2017-11-19 21:15
I would think they would have to assume that everyone now has to do a API call to the market summaries so hopefully they loosened up limits on it. They pretty much just destroyed everyones app until they build out a script to hit there api instead of the socket.  Kind of messed up they didn't give anyone a real warning except for on a slack channel.

**Comment by franciskim722** [comment] 2017-11-20 05:39
Any one email Bittrex support?

**Comment by aloysius-pgast** [comment] 2017-11-20 08:18
Hi. Seems like _SignalR_ method _SubscribeToSummaryDeltas_ now needs to be called (without arguments) for tickers subscriptions (see https://www.bittrex.com/signalr/hubs)

**Comment by webworker01** [comment] 2017-11-20 17:50
@dparlevliet Started experiencing the websockets disconnect error again and the code when attempting to reconnect does not seem to subscribe successfully.  I also dug through the code a bit and couldn't figure how the new force parameter was being used, do you have an updated example please?

**Comment by franciskim722** [comment] 2017-11-21 23:55
Any updates on this issue?

**Comment by aloysius-pgast** [comment] 2017-11-22 08:27
This worked for me
```const bittrex = require('node-bittrex-api');
console.log('Connecting ....');
bittrex.websockets.client(function(wsclient){
    wsclient.serviceHandlers.connected = function () {
        console.log('Connected !');
        wsclient.call('CoreHub', 'SubscribeToSummaryDeltas').done(function(err, result) {
            if (err) {
                return console.error(err);
            }
            if (result === true) {
                console.log('Subscribed to tickers');
                bittrex.websockets.listen(function(data, client) {
                  if (data.M === 'updateSummaryState') {
                    data.A.forEach(function(data_for) {
                      data_for.Deltas.forEach(function(marketsDelta) {
                        console.log('Ticker Update for '+ marketsDelta.MarketName, marketsDelta);
                      });
                    });
                  }
                });
            }
        });
    };
});```

**Comment by franciskim722** [comment] 2017-11-22 23:09
@aloysius-pgast Wow, thanks for the fix! Worked for me, however I need to emit the event twice. Will try and debug on my end

**Comment by enceladus** [comment] 2017-11-23 17:33
Had the same issue, @aloysius-pgast's fix worked for me!

**Comment by aloysius-pgast** [comment] 2017-11-23 20:23
Glad it worked. I supposed it won't be to difficult to do this directly in node.bittrex.api.

**Comment by karimhossenbux** [comment] 2017-11-23 22:11
I've tried @aloysius-pgast code, it's working great when using only once for me. When using more than once, it looks like the web socket keep only the last connection.

I was using `bittrex.websockets.subscribe` before the `updateSummaryState` stopped working on one "coin-info" VueJS component, and I didn't have that issue. Any idea why it behaves differently with the custom client from aloysius-pgast?

Anyway thank you for that piece of code!

**Comment by aloysius-pgast** [comment] 2017-11-23 22:41
No idea why. It was intended to be a quick fix after Bittrex did some changes on their backend. @dparlevliet will probably know better how to deal with this (I gave up trying to change the connection behaviour in the underlying WS client a while ago)

**Comment by dparlevliet** [comment] 2017-11-23 23:23
Sorry, I'm not dead, I'm just ill atm. I'll try get back to this tomorrow.

**Comment by karimhossenbux** [comment] 2017-11-23 23:47
Take care and thank you!
I'll look more into tomorrow

**Comment by karimhossenbux** [comment] 2017-11-24 15:05
I'm guessing that bittrex allow only one active websocket from an IP. Would be logic from them if they have server overload issue

**Comment by aloysius-pgast** [comment] 2017-11-24 15:24
@karimhossenbux : you can have multiple websockets from the same ip (at least it's working fine on my side with 3 distinct websockets). I'm using another lib for SignalR connections though because I had problem with the way connections were managed by signalr-client npm package in the past. It's also possible that my fix broke something in the signalr-client :)

**Closed** 2017-11-26 10:29 UTC
Labels: bittrex issue

**Comment by dparlevliet** [comment] 2017-11-26 10:31
To implement this fix I had to decouple ``listen()`` from ``subscribe()`` so you must now do ``listen()`` if you currently only use ``subscribe``.

**Comment by webworker01** [comment] 2017-11-26 13:14
I'm ready to test when it's updated in npm, thanks for your hard work!

**Comment by kinok** [comment] 2017-11-26 15:51
I had a couple of test, seems to be working fine.
Thanks for your work on this.

**Comment by webworker01** [comment] 2017-11-26 16:17
I am not seeing how the latest change fixes reconnecting after socket is disconnected, but have implemented the latest version and removed the temporary code to test.

**Comment by webworker01** [comment] 2017-11-27 12:57
Okay, I just witnessed my first disconnected websockets and subsequent successful resubscribe. So far so good!

**Comment by webworker01** [comment] 2017-12-31 21:23
Sorry to dig this up again but reconnection does not seem to work again and getting the Negotiate Unknown message.

**Comment by danschnettler** [comment] 2018-02-17 07:11
Does `listen()` work atm? Mine runs for a couple hours then eventually disconnects then the connection is aborted and does not reconnect.
